### ISSUE TITLE
list方法报错

### ISSUE THREAD

**Issue by 18985905246** [SmallOyster/RBAC-CodeIgniter#2]
list()函数是php保留字，但此rbac采用了list所以需要更改routes.php下的路由和方法名即可

**Comment by SmallOyster** [comment]
谢谢你的反馈，我会尽快修复！

**Comment by SmallOyster** [comment]
已修复，详见此Commit：https://github.com/SmallOyster/RBAC-CodeIgniter/commit/5863a36d0951edeef67273c901ad25ff19fc1f76

**衷心感谢您的反馈！也谢谢你对我的项目的支持！**

[ITRClub](https://github.com/ITRClub) CTO -- [@Small Oyster](https://github.com/SmallOyster)
